### ISSUE TITLE
MarketData issue : bid-ask discrepancy between spread and bookorder

### ISSUE THREAD

**Issue by gx-7** [JKorf/CryptoExchange.Net#34]
Hello there,

I hope you are well,

I am dealing with a marketdata issue using `KrakenSymbolOrderBook`.
I found a significant discrepancy between the Spread.bid & ask and the OrderBook BestAsk & BestBid.
The spread is relevant with the true kraken bid-ask marketdata, unfortunatly the Orderbook is not.

Here is an example :

>  KrakenSocketClient KrakenSocketClient = new KrakenSocketClient();
>  await KrakenSocketClient.SubscribeToSpreadUpdatesAsync("BTC/EUR", data => spread = data.Data);
> var orderBook = new KrakenSymbolOrderBook("BTC/EUR", 100);
> orderBook.OnStatusChange += (oldStatus, newStatus) => Console.WriteLine($"Book state changed from {oldStatus} to {newStatus}");
> await orderBook.StartAsync();
>       while (true)   {
>                 var bestBid = orderBook.BestBid;
>                 var bestAsk = orderBook.BestAsk;
> Console.WriteLine(DateTime.UtcNow + "Spread    Ask=" + spread.Ask + " Bid=" + spread.Bid);
> Console.WriteLine(DateTime.UtcNow + "OrderBook Ask=" + bestAsk.Price + " Bid=" + bestBid.Price);
> Console.WriteLine(DateTime.UtcNow + "Diff      " + (spread.Ask - bestAsk.Price) + " Bid=" + (spread.Bid-bestBid.Price));
>  if (bestAsk.Price < bestBid.Price)  {
>  Console.WriteLine(DateTime.UtcNow + " ERROR orderBook Crossed Ask=" + bestAsk.Price + " Bid=" + bestBid.Price);
>                 }
>             }
> 
Console :
![bookorder_bestBidAsk_synchro_issue_2020-march-23](https://user-images.githubusercontent.com/18405940/77328540-f67b2980-6d1c-11ea-813f-eea9bb7b4894.png)

Your help would be welcome :)

Thanks

**Comment by gx-7** [comment]
FYI : I have this issue with Bitfinex too.
![bitfinex issue](https://user-images.githubusercontent.com/18405940/77420112-c6d62b00-6dc9-11ea-815e-382b8b4061f8.png)

**Comment by gx-7** [comment]
FYI : the SymbolOrderBook looks good using BinanceSymbolOrderBook.

**Comment by MatheusGrijo** [comment]
Any solution?

**Comment by JKorf** [comment]
Hi, I think I've fixed this issue. Please let me know if the latest version is working for you.

For anyone interested; 
I've fixed the possibility of multiple threads waiting for a lock to update the order book. This can cause  the wrong thread to go first as waiting for a look isn't necessarily FIFO. I've added a queue for the updates which fixes this issue.

**Comment by MatheusGrijo** [comment]
> Hi, I think I've fixed this issue. Please let me know if the latest version is working for you.
> 
> For anyone interested;
> I've fixed the possibility of multiple threads waiting for a lock to update the order book. This can cause the wrong thread to go first as waiting for a look isn't necessarily FIFO. I've added a queue for the updates which fixes this issue.

First thing, I love you man! hahahah

I just downloaded the version v 1.0.6 of Kraken on Nugget, I think this is already updated correct?

I would like to donate BTC to you, but I don't know which wallet to send! Do you have skype or telegram?

Strong hug!

**Comment by MatheusGrijo** [comment]
I just tested Kraken, but I still have the same problem = (

I am using the SymbolOrderbook and at some point the orderbook shows that it is synced but the bids data is out of date = (

**Comment by JKorf** [comment]
Kraken has added a checksum to every order book update, which I've implemented in the KrakenSymbolOrderBook implementation. The order book will reconnect if the checksums don't match, so it should always have correct data in the latest version. Let me know if there are any issues.
